import Head from "next/head";
import { useState } from "react";
import { MediaButton, Tab, Text } from "@/components/atoms";
import { TfiLightBulb } from "react-icons/tfi";
import data from "../utils/data.json";
import { DEFAULT_TAB, tabs } from "@/utils/constants";
import { Education, Experience, SkillsSection } from "@/components/organisms";

export default function Home() {
  const [darkMode, setdarkMode] = useState(false);
  const [selectedTab, setTab] = useState("Home");

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Eduardo Vásquez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 md:p-6 pt-8 pb-8 bg-neutral-200 dark:bg-zinc-700 min-h-screen">
        <div className=" bg-zinc-800 dark:bg-black rounded-md shadow-md max-w-5xl m-auto min-h-[90vh]">
          <div
            className="bg-slate-200 dark:bg-zinc-900 p-1 shadow-md border-solid border-x border-y
           border-zinc-800 inline-flex flex-row min-w-full justify-between rounded-t-md"
          >
            <div className="inline-flex flex-row">
              {data.socialMedia.map((social) => {
                return (
                  <MediaButton
                    url={social.url}
                    icon={social.icon}
                    key={social.name}
                  />
                );
              })}
            </div>

            <div className="inline-flex flex-row">
              <TfiLightBulb
                className="cursor-pointer mt-2 mr-3 dark:text-neutral-200"
                onClick={() => setdarkMode(!darkMode)}
              />
            </div>
          </div>

          <div
            className="bg-zinc-700 dark:bg-zinc-800 border-solid border-x border-zinc-800 
          inline-flex min-w-full"
          >
            {tabs.map((tab) => {
              return (
                <Tab
                  key={tab.key}
                  name={tab.name}
                  background={selectedTab === tab.name ? DEFAULT_TAB : ""}
                  action={() => setTab(tab.name)}
                />
              );
            })}
          </div>

          <div className="p-3">
            {selectedTab === "Skills" && <SkillsSection skills={data} />}

            {selectedTab === "Experience" && <Experience exp={data} />}

            {selectedTab === "Home" && <Education ed={data} />}
          </div>
        </div>
      </main>
    </div>
  );
}
